# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:""
url: "https://brstar96.github.io"
date_format: "ordinal"
title: brstar96의 블로그
subtitle: "블로그테스트"
description: "블로그 테스트입니다."
keywords: ML/DL
timezone: Asia/Seoul
encoding: "utf-8"
side_bar_repo_limit: 5
remote_theme : mzlogin/mzlogin.github.io

# ---------------- #
#      Author      #
# ---------------- #
author: Myeong-Gyu.Lee
organization: 
organization_url: 
github_username: brstar96
location: Seoul, South Korea
email: brstar96@naver.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 메인

  -
    href: /categories/
    label: 분류

  -
    href: /links/
    label: 링크

  -
    href: /about/
    label: 소개

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: brstar96/brstar96.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: brstar96
    repo: blog-comments
    oauth:
        client_id: d2e1cbbd298958076462
        client_secret: b42a4178e5fd4a7cf63189ef4b1453b05c375709
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: brstar96
    repo: blog-comments
    clientID: d2e1cbbd298958076462
    clientSecret: b42a4178e5fd4a7cf63189ef4b1453b05c375709
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
